### ISSUE TITLE
Error index out of bound when training

### ISSUE THREAD

**Issue by LPioL** [ryutamatsuno/WillbeNamed#1]
Hello,
I have the following error when I try to apply your method on my multiplex graph of 70 nodes. Any idea ?

d    : 128
k    : 4
lamm : 10
beta : 1
gamma: 1
Traceback (most recent call last):

  File "<ipython-input-348-055b3711f73c>", line 11, in <module>
    model = MELL_model(nb_layers, nb_nodes, False, sorted_matrix_train_edges, EMBED_DIMENSION, 4, 10, 1, 1, eta = 0.075)

  File "/home/winkidogan/Documents/DEV/2018_DeepMultiplex/MELL/MELL.py", line 55, in __init__
    self.zeroEdges = getZeroEdges(L, N, directed, edges)

  File "/home/winkidogan/Documents/DEV/2018_DeepMultiplex/MELL/MELL.py", line 251, in getZeroEdges
    A = adjacencyMatrix(L, N, directed, edges)

  File "/home/winkidogan/Documents/DEV/2018_DeepMultiplex/MELL/MELL.py", line 268, in adjacencyMatrix
    A[e[0]][e[1]][e[2]] = e[3]

IndexError: index 70 is out of bounds for axis 0 with size 70

Best.

**Comment by LPioL** [comment]
Just understood, the model needs as input the number of nodes +1.
Best.
